//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.11 at 03:58:23 AM NDT
//


package gz.azure.xml.furnidata;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roomitemtypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="furnitype" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="defaultdir" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="xdim" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ydim" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="partcolors">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="adurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="buyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="rentofferid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="rentbuyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="bc" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="excludeddynamic" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="customparams" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="specialtype" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="canstandon" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="cansiton" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="canlayon" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="wallitemtypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="furnitype" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="adurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="buyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="rentofferid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="rentbuyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="bc" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="excludeddynamic" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="specialtype" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@SuppressWarnings("ALL")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "roomitemtypes",
        "wallitemtypes"
})
@XmlRootElement(name = "furnidata")
public class Furnidata {

    @XmlElement(required = true)
    private Furnidata.Roomitemtypes roomitemtypes;
    @XmlElement(required = true)
    private Furnidata.Wallitemtypes wallitemtypes;

    /**
     * Gets the value of the roomitemtypes property.
     *
     * @return possible object is
     * {@link Furnidata.Roomitemtypes }
     */
    public Furnidata.Roomitemtypes getRoomitemtypes() {
        return roomitemtypes;
    }

    /**
     * Sets the value of the roomitemtypes property.
     *
     * @param value allowed object is
     *              {@link Furnidata.Roomitemtypes }
     */
    public void setRoomitemtypes(Furnidata.Roomitemtypes value) {
        this.roomitemtypes = value;
    }

    /**
     * Gets the value of the wallitemtypes property.
     *
     * @return possible object is
     * {@link Furnidata.Wallitemtypes }
     */
    public Furnidata.Wallitemtypes getWallitemtypes() {
        return wallitemtypes;
    }

    /**
     * Sets the value of the wallitemtypes property.
     *
     * @param value allowed object is
     *              {@link Furnidata.Wallitemtypes }
     */
    public void setWallitemtypes(Furnidata.Wallitemtypes value) {
        this.wallitemtypes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="furnitype" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="defaultdir" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="xdim" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ydim" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="partcolors">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="adurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="buyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="rentofferid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="rentbuyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="bc" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="excludeddynamic" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="customparams" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="specialtype" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="canstandon" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="cansiton" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="canlayon" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "furnitype"
    })
    public static class Roomitemtypes {

        @XmlElement(required = true)
        List<Furnidata.Roomitemtypes.Furnitype> furnitype;

        /**
         * Gets the value of the furnitype property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the furnitype property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFurnitype().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Furnidata.Roomitemtypes.Furnitype }
         */
        public List<Furnidata.Roomitemtypes.Furnitype> getFurnitype() {
            if (furnitype == null) {
                furnitype = new ArrayList<>();
            }
            return this.furnitype;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="defaultdir" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="xdim" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ydim" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="partcolors">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="adurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="buyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="rentofferid" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="rentbuyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="bc" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="excludeddynamic" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="customparams" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="specialtype" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="canstandon" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="cansiton" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="canlayon" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "revision",
                "defaultdir",
                "xdim",
                "ydim",
                "partcolors",
                "name",
                "description",
                "adurl",
                "offerid",
                "buyout",
                "rentofferid",
                "rentbuyout",
                "bc",
                "excludeddynamic",
                "customparams",
                "specialtype",
                "canstandon",
                "cansiton",
                "canlayon"
        })
        public static class Furnitype {

            int revision;
            int defaultdir;
            int xdim;
            int ydim;
            @XmlElement(required = true)
            Furnidata.Roomitemtypes.Furnitype.Partcolors partcolors;
            @XmlElement(required = true)
            String name;
            @XmlElement(required = true)
            String description;
            @XmlElement(required = true)
            Object adurl;
            int offerid;
            int buyout;
            int rentofferid;
            int rentbuyout;
            int bc;
            int excludeddynamic;
            @XmlElement(required = true)
            Object customparams;
            int specialtype;
            int canstandon;
            int cansiton;
            int canlayon;
            @XmlAttribute(name = "id")
            Integer id;
            @XmlAttribute(name = "classname")
            String classname;

            /**
             * Gets the value of the revision property.
             */
            public int getRevision() {
                return revision;
            }

            /**
             * Sets the value of the revision property.
             */
            public void setRevision(int value) {
                this.revision = value;
            }

            /**
             * Gets the value of the defaultdir property.
             */
            public int getDefaultdir() {
                return defaultdir;
            }

            /**
             * Sets the value of the defaultdir property.
             */
            public void setDefaultdir(int value) {
                this.defaultdir = value;
            }

            /**
             * Gets the value of the xdim property.
             */
            public int getXdim() {
                return xdim;
            }

            /**
             * Sets the value of the xdim property.
             */
            public void setXdim(int value) {
                this.xdim = value;
            }

            /**
             * Gets the value of the ydim property.
             */
            public int getYdim() {
                return ydim;
            }

            /**
             * Sets the value of the ydim property.
             */
            public void setYdim(int value) {
                this.ydim = value;
            }

            /**
             * Gets the value of the partcolors property.
             *
             * @return possible object is
             * {@link Furnidata.Roomitemtypes.Furnitype.Partcolors }
             */
            public Furnidata.Roomitemtypes.Furnitype.Partcolors getPartcolors() {
                return partcolors;
            }

            /**
             * Sets the value of the partcolors property.
             *
             * @param value allowed object is
             *              {@link Furnidata.Roomitemtypes.Furnitype.Partcolors }
             */
            public void setPartcolors(Furnidata.Roomitemtypes.Furnitype.Partcolors value) {
                this.partcolors = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the adurl property.
             *
             * @return possible object is
             * {@link Object }
             */
            public Object getAdurl() {
                return adurl;
            }

            /**
             * Sets the value of the adurl property.
             *
             * @param value allowed object is
             *              {@link Object }
             */
            public void setAdurl(Object value) {
                this.adurl = value;
            }

            /**
             * Gets the value of the offerid property.
             */
            public int getOfferid() {
                return offerid;
            }

            /**
             * Sets the value of the offerid property.
             */
            public void setOfferid(int value) {
                this.offerid = value;
            }

            /**
             * Gets the value of the buyout property.
             */
            public int getBuyout() {
                return buyout;
            }

            /**
             * Sets the value of the buyout property.
             */
            public void setBuyout(int value) {
                this.buyout = value;
            }

            /**
             * Gets the value of the rentofferid property.
             */
            public int getRentofferid() {
                return rentofferid;
            }

            /**
             * Sets the value of the rentofferid property.
             */
            public void setRentofferid(int value) {
                this.rentofferid = value;
            }

            /**
             * Gets the value of the rentbuyout property.
             */
            public int getRentbuyout() {
                return rentbuyout;
            }

            /**
             * Sets the value of the rentbuyout property.
             */
            public void setRentbuyout(int value) {
                this.rentbuyout = value;
            }

            /**
             * Gets the value of the bc property.
             */
            public int getBc() {
                return bc;
            }

            /**
             * Sets the value of the bc property.
             */
            public void setBc(int value) {
                this.bc = value;
            }

            /**
             * Gets the value of the excludeddynamic property.
             */
            public int getExcludeddynamic() {
                return excludeddynamic;
            }

            /**
             * Sets the value of the excludeddynamic property.
             */
            public void setExcludeddynamic(int value) {
                this.excludeddynamic = value;
            }

            /**
             * Gets the value of the customparams property.
             *
             * @return possible object is
             * {@link Object }
             */
            public Object getCustomparams() {
                return customparams;
            }

            /**
             * Sets the value of the customparams property.
             *
             * @param value allowed object is
             *              {@link Object }
             */
            public void setCustomparams(Object value) {
                this.customparams = value;
            }

            /**
             * Gets the value of the specialtype property.
             */
            public int getSpecialtype() {
                return specialtype;
            }

            /**
             * Sets the value of the specialtype property.
             */
            public void setSpecialtype(int value) {
                this.specialtype = value;
            }

            /**
             * Gets the value of the canstandon property.
             */
            public int getCanstandon() {
                return canstandon;
            }

            /**
             * Sets the value of the canstandon property.
             */
            public void setCanstandon(int value) {
                this.canstandon = value;
            }

            /**
             * Gets the value of the cansiton property.
             */
            public int getCansiton() {
                return cansiton;
            }

            /**
             * Sets the value of the cansiton property.
             */
            public void setCansiton(int value) {
                this.cansiton = value;
            }

            /**
             * Gets the value of the canlayon property.
             */
            public int getCanlayon() {
                return canlayon;
            }

            /**
             * Sets the value of the canlayon property.
             */
            public void setCanlayon(int value) {
                this.canlayon = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             * {@link Integer }
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link Integer }
             */
            public void setId(Integer value) {
                this.id = value;
            }

            /**
             * Gets the value of the classname property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getClassname() {
                return classname;
            }

            /**
             * Sets the value of the classname property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setClassname(String value) {
                this.classname = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "color"
            })
            public static class Partcolors {

                @XmlElement(required = true)
                List<String> color;

                /**
                 * Gets the value of the color property.
                 * <p>
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the color property.
                 * <p>
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getColor().add(newItem);
                 * </pre>
                 * <p>
                 * <p>
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 */
                public List<String> getColor() {
                    if (color == null) {
                        color = new ArrayList<>();
                    }
                    return this.color;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="furnitype" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="adurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="buyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="rentofferid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="rentbuyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="bc" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="excludeddynamic" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="specialtype" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "furnitype"
    })
    public static class Wallitemtypes {

        @XmlElement(required = true)
        List<Furnidata.Wallitemtypes.Furnitype> furnitype;

        /**
         * Gets the value of the furnitype property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the furnitype property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFurnitype().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Furnidata.Wallitemtypes.Furnitype }
         */
        public List<Furnidata.Wallitemtypes.Furnitype> getFurnitype() {
            if (furnitype == null) {
                furnitype = new ArrayList<>();
            }
            return this.furnitype;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="adurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="buyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="rentofferid" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="rentbuyout" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="bc" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="excludeddynamic" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="specialtype" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "revision",
                "name",
                "description",
                "adurl",
                "offerid",
                "buyout",
                "rentofferid",
                "rentbuyout",
                "bc",
                "excludeddynamic",
                "specialtype"
        })
        public static class Furnitype {

            int revision;
            @XmlElement(required = true)
            String name;
            @XmlElement(required = true)
            String description;
            @XmlElement(required = true)
            Object adurl;
            int offerid;
            int buyout;
            int rentofferid;
            int rentbuyout;
            int bc;
            int excludeddynamic;
            int specialtype;
            @XmlAttribute(name = "id")
            Integer id;
            @XmlAttribute(name = "classname")
            String classname;

            /**
             * Gets the value of the revision property.
             */
            public int getRevision() {
                return revision;
            }

            /**
             * Sets the value of the revision property.
             */
            public void setRevision(int value) {
                this.revision = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the adurl property.
             *
             * @return possible object is
             * {@link Object }
             */
            public Object getAdurl() {
                return adurl;
            }

            /**
             * Sets the value of the adurl property.
             *
             * @param value allowed object is
             *              {@link Object }
             */
            public void setAdurl(Object value) {
                this.adurl = value;
            }

            /**
             * Gets the value of the offerid property.
             */
            public int getOfferid() {
                return offerid;
            }

            /**
             * Sets the value of the offerid property.
             */
            public void setOfferid(int value) {
                this.offerid = value;
            }

            /**
             * Gets the value of the buyout property.
             */
            public int getBuyout() {
                return buyout;
            }

            /**
             * Sets the value of the buyout property.
             */
            public void setBuyout(int value) {
                this.buyout = value;
            }

            /**
             * Gets the value of the rentofferid property.
             */
            public int getRentofferid() {
                return rentofferid;
            }

            /**
             * Sets the value of the rentofferid property.
             */
            public void setRentofferid(int value) {
                this.rentofferid = value;
            }

            /**
             * Gets the value of the rentbuyout property.
             */
            public int getRentbuyout() {
                return rentbuyout;
            }

            /**
             * Sets the value of the rentbuyout property.
             */
            public void setRentbuyout(int value) {
                this.rentbuyout = value;
            }

            /**
             * Gets the value of the bc property.
             */
            public int getBc() {
                return bc;
            }

            /**
             * Sets the value of the bc property.
             */
            public void setBc(int value) {
                this.bc = value;
            }

            /**
             * Gets the value of the excludeddynamic property.
             */
            public int getExcludeddynamic() {
                return excludeddynamic;
            }

            /**
             * Sets the value of the excludeddynamic property.
             */
            public void setExcludeddynamic(int value) {
                this.excludeddynamic = value;
            }

            /**
             * Gets the value of the specialtype property.
             */
            public int getSpecialtype() {
                return specialtype;
            }

            /**
             * Sets the value of the specialtype property.
             */
            public void setSpecialtype(int value) {
                this.specialtype = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             * {@link Integer }
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link Integer }
             */
            public void setId(Integer value) {
                this.id = value;
            }

            /**
             * Gets the value of the classname property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getClassname() {
                return classname;
            }

            /**
             * Sets the value of the classname property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setClassname(String value) {
                this.classname = value;
            }

        }

    }

}
